package com.jxufe.entity.eva_sso;

import java.math.BigDecimal;
import java.util.Date;

public class SysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.USERID
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String USERID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.USERNAME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String USERNAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.PASSWD
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String PASSWD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.DESCRIPTION
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String DESCRIPTION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.CREATETIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private Date CREATETIME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.USERSTATE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String USERSTATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.LOCKTIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private Date LOCKTIME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.UNLOCKTIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private Date UNLOCKTIME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.LOCKREASON
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String LOCKREASON;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.USEREXPIREDATE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private Date USEREXPIREDATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.PWEXPIRETYPE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String PWEXPIRETYPE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.PWEXPIREDATE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private Date PWEXPIREDATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.PWEDITDATE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private Date PWEDITDATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.ORGID
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String ORGID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.USERTYPE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String USERTYPE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.DISPLAYNAME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String DISPLAYNAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.TEL
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String TEL;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.MOBILE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String MOBILE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.EMAIL
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String EMAIL;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.USERADDR
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String USERADDR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.CREATORID
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String CREATORID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.FAILNO
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private Short FAILNO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.SALT
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String SALT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.IDCARD
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String IDCARD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.CAKEY
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String CAKEY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.LOGINTIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private Date LOGINTIME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.USERID01
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String USERID01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.USERID02
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String USERID02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.USERID03
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String USERID03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.USERQX
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String USERQX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.USERKIND
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String USERKIND;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.LASTEDITTIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private Date LASTEDITTIME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.FORCEEDITPWD
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String FORCEEDITPWD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.AAZ198
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private BigDecimal AAZ198;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EVA_SSO.SYSUSER.REMARK
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    private String REMARK;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.USERID
     *
     * @return the value of EVA_SSO.SYSUSER.USERID
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getUSERID() {
        return USERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.USERID
     *
     * @param USERID the value for EVA_SSO.SYSUSER.USERID
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setUSERID(String USERID) {
        this.USERID = USERID == null ? null : USERID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.USERNAME
     *
     * @return the value of EVA_SSO.SYSUSER.USERNAME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getUSERNAME() {
        return USERNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.USERNAME
     *
     * @param USERNAME the value for EVA_SSO.SYSUSER.USERNAME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setUSERNAME(String USERNAME) {
        this.USERNAME = USERNAME == null ? null : USERNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.PASSWD
     *
     * @return the value of EVA_SSO.SYSUSER.PASSWD
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getPASSWD() {
        return PASSWD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.PASSWD
     *
     * @param PASSWD the value for EVA_SSO.SYSUSER.PASSWD
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setPASSWD(String PASSWD) {
        this.PASSWD = PASSWD == null ? null : PASSWD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.DESCRIPTION
     *
     * @return the value of EVA_SSO.SYSUSER.DESCRIPTION
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.DESCRIPTION
     *
     * @param DESCRIPTION the value for EVA_SSO.SYSUSER.DESCRIPTION
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.CREATETIME
     *
     * @return the value of EVA_SSO.SYSUSER.CREATETIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public Date getCREATETIME() {
        return CREATETIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.CREATETIME
     *
     * @param CREATETIME the value for EVA_SSO.SYSUSER.CREATETIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setCREATETIME(Date CREATETIME) {
        this.CREATETIME = CREATETIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.USERSTATE
     *
     * @return the value of EVA_SSO.SYSUSER.USERSTATE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getUSERSTATE() {
        return USERSTATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.USERSTATE
     *
     * @param USERSTATE the value for EVA_SSO.SYSUSER.USERSTATE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setUSERSTATE(String USERSTATE) {
        this.USERSTATE = USERSTATE == null ? null : USERSTATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.LOCKTIME
     *
     * @return the value of EVA_SSO.SYSUSER.LOCKTIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public Date getLOCKTIME() {
        return LOCKTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.LOCKTIME
     *
     * @param LOCKTIME the value for EVA_SSO.SYSUSER.LOCKTIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setLOCKTIME(Date LOCKTIME) {
        this.LOCKTIME = LOCKTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.UNLOCKTIME
     *
     * @return the value of EVA_SSO.SYSUSER.UNLOCKTIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public Date getUNLOCKTIME() {
        return UNLOCKTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.UNLOCKTIME
     *
     * @param UNLOCKTIME the value for EVA_SSO.SYSUSER.UNLOCKTIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setUNLOCKTIME(Date UNLOCKTIME) {
        this.UNLOCKTIME = UNLOCKTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.LOCKREASON
     *
     * @return the value of EVA_SSO.SYSUSER.LOCKREASON
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getLOCKREASON() {
        return LOCKREASON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.LOCKREASON
     *
     * @param LOCKREASON the value for EVA_SSO.SYSUSER.LOCKREASON
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setLOCKREASON(String LOCKREASON) {
        this.LOCKREASON = LOCKREASON == null ? null : LOCKREASON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.USEREXPIREDATE
     *
     * @return the value of EVA_SSO.SYSUSER.USEREXPIREDATE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public Date getUSEREXPIREDATE() {
        return USEREXPIREDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.USEREXPIREDATE
     *
     * @param USEREXPIREDATE the value for EVA_SSO.SYSUSER.USEREXPIREDATE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setUSEREXPIREDATE(Date USEREXPIREDATE) {
        this.USEREXPIREDATE = USEREXPIREDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.PWEXPIRETYPE
     *
     * @return the value of EVA_SSO.SYSUSER.PWEXPIRETYPE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getPWEXPIRETYPE() {
        return PWEXPIRETYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.PWEXPIRETYPE
     *
     * @param PWEXPIRETYPE the value for EVA_SSO.SYSUSER.PWEXPIRETYPE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setPWEXPIRETYPE(String PWEXPIRETYPE) {
        this.PWEXPIRETYPE = PWEXPIRETYPE == null ? null : PWEXPIRETYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.PWEXPIREDATE
     *
     * @return the value of EVA_SSO.SYSUSER.PWEXPIREDATE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public Date getPWEXPIREDATE() {
        return PWEXPIREDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.PWEXPIREDATE
     *
     * @param PWEXPIREDATE the value for EVA_SSO.SYSUSER.PWEXPIREDATE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setPWEXPIREDATE(Date PWEXPIREDATE) {
        this.PWEXPIREDATE = PWEXPIREDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.PWEDITDATE
     *
     * @return the value of EVA_SSO.SYSUSER.PWEDITDATE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public Date getPWEDITDATE() {
        return PWEDITDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.PWEDITDATE
     *
     * @param PWEDITDATE the value for EVA_SSO.SYSUSER.PWEDITDATE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setPWEDITDATE(Date PWEDITDATE) {
        this.PWEDITDATE = PWEDITDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.ORGID
     *
     * @return the value of EVA_SSO.SYSUSER.ORGID
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getORGID() {
        return ORGID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.ORGID
     *
     * @param ORGID the value for EVA_SSO.SYSUSER.ORGID
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setORGID(String ORGID) {
        this.ORGID = ORGID == null ? null : ORGID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.USERTYPE
     *
     * @return the value of EVA_SSO.SYSUSER.USERTYPE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getUSERTYPE() {
        return USERTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.USERTYPE
     *
     * @param USERTYPE the value for EVA_SSO.SYSUSER.USERTYPE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setUSERTYPE(String USERTYPE) {
        this.USERTYPE = USERTYPE == null ? null : USERTYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.DISPLAYNAME
     *
     * @return the value of EVA_SSO.SYSUSER.DISPLAYNAME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getDISPLAYNAME() {
        return DISPLAYNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.DISPLAYNAME
     *
     * @param DISPLAYNAME the value for EVA_SSO.SYSUSER.DISPLAYNAME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setDISPLAYNAME(String DISPLAYNAME) {
        this.DISPLAYNAME = DISPLAYNAME == null ? null : DISPLAYNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.TEL
     *
     * @return the value of EVA_SSO.SYSUSER.TEL
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getTEL() {
        return TEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.TEL
     *
     * @param TEL the value for EVA_SSO.SYSUSER.TEL
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setTEL(String TEL) {
        this.TEL = TEL == null ? null : TEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.MOBILE
     *
     * @return the value of EVA_SSO.SYSUSER.MOBILE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getMOBILE() {
        return MOBILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.MOBILE
     *
     * @param MOBILE the value for EVA_SSO.SYSUSER.MOBILE
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setMOBILE(String MOBILE) {
        this.MOBILE = MOBILE == null ? null : MOBILE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.EMAIL
     *
     * @return the value of EVA_SSO.SYSUSER.EMAIL
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getEMAIL() {
        return EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.EMAIL
     *
     * @param EMAIL the value for EVA_SSO.SYSUSER.EMAIL
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setEMAIL(String EMAIL) {
        this.EMAIL = EMAIL == null ? null : EMAIL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.USERADDR
     *
     * @return the value of EVA_SSO.SYSUSER.USERADDR
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getUSERADDR() {
        return USERADDR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.USERADDR
     *
     * @param USERADDR the value for EVA_SSO.SYSUSER.USERADDR
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setUSERADDR(String USERADDR) {
        this.USERADDR = USERADDR == null ? null : USERADDR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.CREATORID
     *
     * @return the value of EVA_SSO.SYSUSER.CREATORID
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getCREATORID() {
        return CREATORID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.CREATORID
     *
     * @param CREATORID the value for EVA_SSO.SYSUSER.CREATORID
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setCREATORID(String CREATORID) {
        this.CREATORID = CREATORID == null ? null : CREATORID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.FAILNO
     *
     * @return the value of EVA_SSO.SYSUSER.FAILNO
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public Short getFAILNO() {
        return FAILNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.FAILNO
     *
     * @param FAILNO the value for EVA_SSO.SYSUSER.FAILNO
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setFAILNO(Short FAILNO) {
        this.FAILNO = FAILNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.SALT
     *
     * @return the value of EVA_SSO.SYSUSER.SALT
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getSALT() {
        return SALT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.SALT
     *
     * @param SALT the value for EVA_SSO.SYSUSER.SALT
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setSALT(String SALT) {
        this.SALT = SALT == null ? null : SALT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.IDCARD
     *
     * @return the value of EVA_SSO.SYSUSER.IDCARD
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getIDCARD() {
        return IDCARD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.IDCARD
     *
     * @param IDCARD the value for EVA_SSO.SYSUSER.IDCARD
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setIDCARD(String IDCARD) {
        this.IDCARD = IDCARD == null ? null : IDCARD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.CAKEY
     *
     * @return the value of EVA_SSO.SYSUSER.CAKEY
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getCAKEY() {
        return CAKEY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.CAKEY
     *
     * @param CAKEY the value for EVA_SSO.SYSUSER.CAKEY
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setCAKEY(String CAKEY) {
        this.CAKEY = CAKEY == null ? null : CAKEY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.LOGINTIME
     *
     * @return the value of EVA_SSO.SYSUSER.LOGINTIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public Date getLOGINTIME() {
        return LOGINTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.LOGINTIME
     *
     * @param LOGINTIME the value for EVA_SSO.SYSUSER.LOGINTIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setLOGINTIME(Date LOGINTIME) {
        this.LOGINTIME = LOGINTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.USERID01
     *
     * @return the value of EVA_SSO.SYSUSER.USERID01
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getUSERID01() {
        return USERID01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.USERID01
     *
     * @param USERID01 the value for EVA_SSO.SYSUSER.USERID01
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setUSERID01(String USERID01) {
        this.USERID01 = USERID01 == null ? null : USERID01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.USERID02
     *
     * @return the value of EVA_SSO.SYSUSER.USERID02
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getUSERID02() {
        return USERID02;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.USERID02
     *
     * @param USERID02 the value for EVA_SSO.SYSUSER.USERID02
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setUSERID02(String USERID02) {
        this.USERID02 = USERID02 == null ? null : USERID02.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.USERID03
     *
     * @return the value of EVA_SSO.SYSUSER.USERID03
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getUSERID03() {
        return USERID03;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.USERID03
     *
     * @param USERID03 the value for EVA_SSO.SYSUSER.USERID03
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setUSERID03(String USERID03) {
        this.USERID03 = USERID03 == null ? null : USERID03.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.USERQX
     *
     * @return the value of EVA_SSO.SYSUSER.USERQX
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getUSERQX() {
        return USERQX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.USERQX
     *
     * @param USERQX the value for EVA_SSO.SYSUSER.USERQX
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setUSERQX(String USERQX) {
        this.USERQX = USERQX == null ? null : USERQX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.USERKIND
     *
     * @return the value of EVA_SSO.SYSUSER.USERKIND
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getUSERKIND() {
        return USERKIND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.USERKIND
     *
     * @param USERKIND the value for EVA_SSO.SYSUSER.USERKIND
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setUSERKIND(String USERKIND) {
        this.USERKIND = USERKIND == null ? null : USERKIND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.LASTEDITTIME
     *
     * @return the value of EVA_SSO.SYSUSER.LASTEDITTIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public Date getLASTEDITTIME() {
        return LASTEDITTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.LASTEDITTIME
     *
     * @param LASTEDITTIME the value for EVA_SSO.SYSUSER.LASTEDITTIME
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setLASTEDITTIME(Date LASTEDITTIME) {
        this.LASTEDITTIME = LASTEDITTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.FORCEEDITPWD
     *
     * @return the value of EVA_SSO.SYSUSER.FORCEEDITPWD
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getFORCEEDITPWD() {
        return FORCEEDITPWD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.FORCEEDITPWD
     *
     * @param FORCEEDITPWD the value for EVA_SSO.SYSUSER.FORCEEDITPWD
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setFORCEEDITPWD(String FORCEEDITPWD) {
        this.FORCEEDITPWD = FORCEEDITPWD == null ? null : FORCEEDITPWD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.AAZ198
     *
     * @return the value of EVA_SSO.SYSUSER.AAZ198
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public BigDecimal getAAZ198() {
        return AAZ198;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.AAZ198
     *
     * @param AAZ198 the value for EVA_SSO.SYSUSER.AAZ198
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setAAZ198(BigDecimal AAZ198) {
        this.AAZ198 = AAZ198;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EVA_SSO.SYSUSER.REMARK
     *
     * @return the value of EVA_SSO.SYSUSER.REMARK
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public String getREMARK() {
        return REMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EVA_SSO.SYSUSER.REMARK
     *
     * @param REMARK the value for EVA_SSO.SYSUSER.REMARK
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    public void setREMARK(String REMARK) {
        this.REMARK = REMARK == null ? null : REMARK.trim();
    }
}