package com.jxufe.entity.eva_sso;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    public SysUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUSERIDIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUSERIDIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUSERIDEqualTo(String value) {
            addCriterion("USERID =", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDNotEqualTo(String value) {
            addCriterion("USERID <>", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDGreaterThan(String value) {
            addCriterion("USERID >", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDLessThan(String value) {
            addCriterion("USERID <", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDLike(String value) {
            addCriterion("USERID like", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDNotLike(String value) {
            addCriterion("USERID not like", value, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDIn(List<String> values) {
            addCriterion("USERID in", values, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDNotIn(List<String> values) {
            addCriterion("USERID not in", values, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERIDNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "USERID");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEIsNull() {
            addCriterion("USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEIsNotNull() {
            addCriterion("USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEEqualTo(String value) {
            addCriterion("USERNAME =", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMENotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEGreaterThan(String value) {
            addCriterion("USERNAME >", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMELessThan(String value) {
            addCriterion("USERNAME <", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMELessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMELike(String value) {
            addCriterion("USERNAME like", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMENotLike(String value) {
            addCriterion("USERNAME not like", value, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEIn(List<String> values) {
            addCriterion("USERNAME in", values, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMENotIn(List<String> values) {
            addCriterion("USERNAME not in", values, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMEBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andUSERNAMENotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "USERNAME");
            return (Criteria) this;
        }

        public Criteria andPASSWDIsNull() {
            addCriterion("PASSWD is null");
            return (Criteria) this;
        }

        public Criteria andPASSWDIsNotNull() {
            addCriterion("PASSWD is not null");
            return (Criteria) this;
        }

        public Criteria andPASSWDEqualTo(String value) {
            addCriterion("PASSWD =", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDNotEqualTo(String value) {
            addCriterion("PASSWD <>", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDGreaterThan(String value) {
            addCriterion("PASSWD >", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWD >=", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDLessThan(String value) {
            addCriterion("PASSWD <", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDLessThanOrEqualTo(String value) {
            addCriterion("PASSWD <=", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDLike(String value) {
            addCriterion("PASSWD like", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDNotLike(String value) {
            addCriterion("PASSWD not like", value, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDIn(List<String> values) {
            addCriterion("PASSWD in", values, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDNotIn(List<String> values) {
            addCriterion("PASSWD not in", values, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDBetween(String value1, String value2) {
            addCriterion("PASSWD between", value1, value2, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andPASSWDNotBetween(String value1, String value2) {
            addCriterion("PASSWD not between", value1, value2, "PASSWD");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONLike(String value) {
            addCriterion("DESCRIPTION like", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andDESCRIPTIONNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "DESCRIPTION");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEIsNull() {
            addCriterion("CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEIsNotNull() {
            addCriterion("CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEEqualTo(Date value) {
            addCriterion("CREATETIME =", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMENotEqualTo(Date value) {
            addCriterion("CREATETIME <>", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEGreaterThan(Date value) {
            addCriterion("CREATETIME >", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATETIME >=", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMELessThan(Date value) {
            addCriterion("CREATETIME <", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMELessThanOrEqualTo(Date value) {
            addCriterion("CREATETIME <=", value, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEIn(List<Date> values) {
            addCriterion("CREATETIME in", values, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMENotIn(List<Date> values) {
            addCriterion("CREATETIME not in", values, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMEBetween(Date value1, Date value2) {
            addCriterion("CREATETIME between", value1, value2, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andCREATETIMENotBetween(Date value1, Date value2) {
            addCriterion("CREATETIME not between", value1, value2, "CREATETIME");
            return (Criteria) this;
        }

        public Criteria andUSERSTATEIsNull() {
            addCriterion("USERSTATE is null");
            return (Criteria) this;
        }

        public Criteria andUSERSTATEIsNotNull() {
            addCriterion("USERSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andUSERSTATEEqualTo(String value) {
            addCriterion("USERSTATE =", value, "USERSTATE");
            return (Criteria) this;
        }

        public Criteria andUSERSTATENotEqualTo(String value) {
            addCriterion("USERSTATE <>", value, "USERSTATE");
            return (Criteria) this;
        }

        public Criteria andUSERSTATEGreaterThan(String value) {
            addCriterion("USERSTATE >", value, "USERSTATE");
            return (Criteria) this;
        }

        public Criteria andUSERSTATEGreaterThanOrEqualTo(String value) {
            addCriterion("USERSTATE >=", value, "USERSTATE");
            return (Criteria) this;
        }

        public Criteria andUSERSTATELessThan(String value) {
            addCriterion("USERSTATE <", value, "USERSTATE");
            return (Criteria) this;
        }

        public Criteria andUSERSTATELessThanOrEqualTo(String value) {
            addCriterion("USERSTATE <=", value, "USERSTATE");
            return (Criteria) this;
        }

        public Criteria andUSERSTATELike(String value) {
            addCriterion("USERSTATE like", value, "USERSTATE");
            return (Criteria) this;
        }

        public Criteria andUSERSTATENotLike(String value) {
            addCriterion("USERSTATE not like", value, "USERSTATE");
            return (Criteria) this;
        }

        public Criteria andUSERSTATEIn(List<String> values) {
            addCriterion("USERSTATE in", values, "USERSTATE");
            return (Criteria) this;
        }

        public Criteria andUSERSTATENotIn(List<String> values) {
            addCriterion("USERSTATE not in", values, "USERSTATE");
            return (Criteria) this;
        }

        public Criteria andUSERSTATEBetween(String value1, String value2) {
            addCriterion("USERSTATE between", value1, value2, "USERSTATE");
            return (Criteria) this;
        }

        public Criteria andUSERSTATENotBetween(String value1, String value2) {
            addCriterion("USERSTATE not between", value1, value2, "USERSTATE");
            return (Criteria) this;
        }

        public Criteria andLOCKTIMEIsNull() {
            addCriterion("LOCKTIME is null");
            return (Criteria) this;
        }

        public Criteria andLOCKTIMEIsNotNull() {
            addCriterion("LOCKTIME is not null");
            return (Criteria) this;
        }

        public Criteria andLOCKTIMEEqualTo(Date value) {
            addCriterion("LOCKTIME =", value, "LOCKTIME");
            return (Criteria) this;
        }

        public Criteria andLOCKTIMENotEqualTo(Date value) {
            addCriterion("LOCKTIME <>", value, "LOCKTIME");
            return (Criteria) this;
        }

        public Criteria andLOCKTIMEGreaterThan(Date value) {
            addCriterion("LOCKTIME >", value, "LOCKTIME");
            return (Criteria) this;
        }

        public Criteria andLOCKTIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("LOCKTIME >=", value, "LOCKTIME");
            return (Criteria) this;
        }

        public Criteria andLOCKTIMELessThan(Date value) {
            addCriterion("LOCKTIME <", value, "LOCKTIME");
            return (Criteria) this;
        }

        public Criteria andLOCKTIMELessThanOrEqualTo(Date value) {
            addCriterion("LOCKTIME <=", value, "LOCKTIME");
            return (Criteria) this;
        }

        public Criteria andLOCKTIMEIn(List<Date> values) {
            addCriterion("LOCKTIME in", values, "LOCKTIME");
            return (Criteria) this;
        }

        public Criteria andLOCKTIMENotIn(List<Date> values) {
            addCriterion("LOCKTIME not in", values, "LOCKTIME");
            return (Criteria) this;
        }

        public Criteria andLOCKTIMEBetween(Date value1, Date value2) {
            addCriterion("LOCKTIME between", value1, value2, "LOCKTIME");
            return (Criteria) this;
        }

        public Criteria andLOCKTIMENotBetween(Date value1, Date value2) {
            addCriterion("LOCKTIME not between", value1, value2, "LOCKTIME");
            return (Criteria) this;
        }

        public Criteria andUNLOCKTIMEIsNull() {
            addCriterion("UNLOCKTIME is null");
            return (Criteria) this;
        }

        public Criteria andUNLOCKTIMEIsNotNull() {
            addCriterion("UNLOCKTIME is not null");
            return (Criteria) this;
        }

        public Criteria andUNLOCKTIMEEqualTo(Date value) {
            addCriterion("UNLOCKTIME =", value, "UNLOCKTIME");
            return (Criteria) this;
        }

        public Criteria andUNLOCKTIMENotEqualTo(Date value) {
            addCriterion("UNLOCKTIME <>", value, "UNLOCKTIME");
            return (Criteria) this;
        }

        public Criteria andUNLOCKTIMEGreaterThan(Date value) {
            addCriterion("UNLOCKTIME >", value, "UNLOCKTIME");
            return (Criteria) this;
        }

        public Criteria andUNLOCKTIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("UNLOCKTIME >=", value, "UNLOCKTIME");
            return (Criteria) this;
        }

        public Criteria andUNLOCKTIMELessThan(Date value) {
            addCriterion("UNLOCKTIME <", value, "UNLOCKTIME");
            return (Criteria) this;
        }

        public Criteria andUNLOCKTIMELessThanOrEqualTo(Date value) {
            addCriterion("UNLOCKTIME <=", value, "UNLOCKTIME");
            return (Criteria) this;
        }

        public Criteria andUNLOCKTIMEIn(List<Date> values) {
            addCriterion("UNLOCKTIME in", values, "UNLOCKTIME");
            return (Criteria) this;
        }

        public Criteria andUNLOCKTIMENotIn(List<Date> values) {
            addCriterion("UNLOCKTIME not in", values, "UNLOCKTIME");
            return (Criteria) this;
        }

        public Criteria andUNLOCKTIMEBetween(Date value1, Date value2) {
            addCriterion("UNLOCKTIME between", value1, value2, "UNLOCKTIME");
            return (Criteria) this;
        }

        public Criteria andUNLOCKTIMENotBetween(Date value1, Date value2) {
            addCriterion("UNLOCKTIME not between", value1, value2, "UNLOCKTIME");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONIsNull() {
            addCriterion("LOCKREASON is null");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONIsNotNull() {
            addCriterion("LOCKREASON is not null");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONEqualTo(String value) {
            addCriterion("LOCKREASON =", value, "LOCKREASON");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONNotEqualTo(String value) {
            addCriterion("LOCKREASON <>", value, "LOCKREASON");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONGreaterThan(String value) {
            addCriterion("LOCKREASON >", value, "LOCKREASON");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONGreaterThanOrEqualTo(String value) {
            addCriterion("LOCKREASON >=", value, "LOCKREASON");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONLessThan(String value) {
            addCriterion("LOCKREASON <", value, "LOCKREASON");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONLessThanOrEqualTo(String value) {
            addCriterion("LOCKREASON <=", value, "LOCKREASON");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONLike(String value) {
            addCriterion("LOCKREASON like", value, "LOCKREASON");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONNotLike(String value) {
            addCriterion("LOCKREASON not like", value, "LOCKREASON");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONIn(List<String> values) {
            addCriterion("LOCKREASON in", values, "LOCKREASON");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONNotIn(List<String> values) {
            addCriterion("LOCKREASON not in", values, "LOCKREASON");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONBetween(String value1, String value2) {
            addCriterion("LOCKREASON between", value1, value2, "LOCKREASON");
            return (Criteria) this;
        }

        public Criteria andLOCKREASONNotBetween(String value1, String value2) {
            addCriterion("LOCKREASON not between", value1, value2, "LOCKREASON");
            return (Criteria) this;
        }

        public Criteria andUSEREXPIREDATEIsNull() {
            addCriterion("USEREXPIREDATE is null");
            return (Criteria) this;
        }

        public Criteria andUSEREXPIREDATEIsNotNull() {
            addCriterion("USEREXPIREDATE is not null");
            return (Criteria) this;
        }

        public Criteria andUSEREXPIREDATEEqualTo(Date value) {
            addCriterion("USEREXPIREDATE =", value, "USEREXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andUSEREXPIREDATENotEqualTo(Date value) {
            addCriterion("USEREXPIREDATE <>", value, "USEREXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andUSEREXPIREDATEGreaterThan(Date value) {
            addCriterion("USEREXPIREDATE >", value, "USEREXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andUSEREXPIREDATEGreaterThanOrEqualTo(Date value) {
            addCriterion("USEREXPIREDATE >=", value, "USEREXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andUSEREXPIREDATELessThan(Date value) {
            addCriterion("USEREXPIREDATE <", value, "USEREXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andUSEREXPIREDATELessThanOrEqualTo(Date value) {
            addCriterion("USEREXPIREDATE <=", value, "USEREXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andUSEREXPIREDATEIn(List<Date> values) {
            addCriterion("USEREXPIREDATE in", values, "USEREXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andUSEREXPIREDATENotIn(List<Date> values) {
            addCriterion("USEREXPIREDATE not in", values, "USEREXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andUSEREXPIREDATEBetween(Date value1, Date value2) {
            addCriterion("USEREXPIREDATE between", value1, value2, "USEREXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andUSEREXPIREDATENotBetween(Date value1, Date value2) {
            addCriterion("USEREXPIREDATE not between", value1, value2, "USEREXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPEIsNull() {
            addCriterion("PWEXPIRETYPE is null");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPEIsNotNull() {
            addCriterion("PWEXPIRETYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPEEqualTo(String value) {
            addCriterion("PWEXPIRETYPE =", value, "PWEXPIRETYPE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPENotEqualTo(String value) {
            addCriterion("PWEXPIRETYPE <>", value, "PWEXPIRETYPE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPEGreaterThan(String value) {
            addCriterion("PWEXPIRETYPE >", value, "PWEXPIRETYPE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPEGreaterThanOrEqualTo(String value) {
            addCriterion("PWEXPIRETYPE >=", value, "PWEXPIRETYPE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPELessThan(String value) {
            addCriterion("PWEXPIRETYPE <", value, "PWEXPIRETYPE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPELessThanOrEqualTo(String value) {
            addCriterion("PWEXPIRETYPE <=", value, "PWEXPIRETYPE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPELike(String value) {
            addCriterion("PWEXPIRETYPE like", value, "PWEXPIRETYPE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPENotLike(String value) {
            addCriterion("PWEXPIRETYPE not like", value, "PWEXPIRETYPE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPEIn(List<String> values) {
            addCriterion("PWEXPIRETYPE in", values, "PWEXPIRETYPE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPENotIn(List<String> values) {
            addCriterion("PWEXPIRETYPE not in", values, "PWEXPIRETYPE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPEBetween(String value1, String value2) {
            addCriterion("PWEXPIRETYPE between", value1, value2, "PWEXPIRETYPE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIRETYPENotBetween(String value1, String value2) {
            addCriterion("PWEXPIRETYPE not between", value1, value2, "PWEXPIRETYPE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIREDATEIsNull() {
            addCriterion("PWEXPIREDATE is null");
            return (Criteria) this;
        }

        public Criteria andPWEXPIREDATEIsNotNull() {
            addCriterion("PWEXPIREDATE is not null");
            return (Criteria) this;
        }

        public Criteria andPWEXPIREDATEEqualTo(Date value) {
            addCriterion("PWEXPIREDATE =", value, "PWEXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIREDATENotEqualTo(Date value) {
            addCriterion("PWEXPIREDATE <>", value, "PWEXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIREDATEGreaterThan(Date value) {
            addCriterion("PWEXPIREDATE >", value, "PWEXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIREDATEGreaterThanOrEqualTo(Date value) {
            addCriterion("PWEXPIREDATE >=", value, "PWEXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIREDATELessThan(Date value) {
            addCriterion("PWEXPIREDATE <", value, "PWEXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIREDATELessThanOrEqualTo(Date value) {
            addCriterion("PWEXPIREDATE <=", value, "PWEXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIREDATEIn(List<Date> values) {
            addCriterion("PWEXPIREDATE in", values, "PWEXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIREDATENotIn(List<Date> values) {
            addCriterion("PWEXPIREDATE not in", values, "PWEXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIREDATEBetween(Date value1, Date value2) {
            addCriterion("PWEXPIREDATE between", value1, value2, "PWEXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andPWEXPIREDATENotBetween(Date value1, Date value2) {
            addCriterion("PWEXPIREDATE not between", value1, value2, "PWEXPIREDATE");
            return (Criteria) this;
        }

        public Criteria andPWEDITDATEIsNull() {
            addCriterion("PWEDITDATE is null");
            return (Criteria) this;
        }

        public Criteria andPWEDITDATEIsNotNull() {
            addCriterion("PWEDITDATE is not null");
            return (Criteria) this;
        }

        public Criteria andPWEDITDATEEqualTo(Date value) {
            addCriterion("PWEDITDATE =", value, "PWEDITDATE");
            return (Criteria) this;
        }

        public Criteria andPWEDITDATENotEqualTo(Date value) {
            addCriterion("PWEDITDATE <>", value, "PWEDITDATE");
            return (Criteria) this;
        }

        public Criteria andPWEDITDATEGreaterThan(Date value) {
            addCriterion("PWEDITDATE >", value, "PWEDITDATE");
            return (Criteria) this;
        }

        public Criteria andPWEDITDATEGreaterThanOrEqualTo(Date value) {
            addCriterion("PWEDITDATE >=", value, "PWEDITDATE");
            return (Criteria) this;
        }

        public Criteria andPWEDITDATELessThan(Date value) {
            addCriterion("PWEDITDATE <", value, "PWEDITDATE");
            return (Criteria) this;
        }

        public Criteria andPWEDITDATELessThanOrEqualTo(Date value) {
            addCriterion("PWEDITDATE <=", value, "PWEDITDATE");
            return (Criteria) this;
        }

        public Criteria andPWEDITDATEIn(List<Date> values) {
            addCriterion("PWEDITDATE in", values, "PWEDITDATE");
            return (Criteria) this;
        }

        public Criteria andPWEDITDATENotIn(List<Date> values) {
            addCriterion("PWEDITDATE not in", values, "PWEDITDATE");
            return (Criteria) this;
        }

        public Criteria andPWEDITDATEBetween(Date value1, Date value2) {
            addCriterion("PWEDITDATE between", value1, value2, "PWEDITDATE");
            return (Criteria) this;
        }

        public Criteria andPWEDITDATENotBetween(Date value1, Date value2) {
            addCriterion("PWEDITDATE not between", value1, value2, "PWEDITDATE");
            return (Criteria) this;
        }

        public Criteria andORGIDIsNull() {
            addCriterion("ORGID is null");
            return (Criteria) this;
        }

        public Criteria andORGIDIsNotNull() {
            addCriterion("ORGID is not null");
            return (Criteria) this;
        }

        public Criteria andORGIDEqualTo(String value) {
            addCriterion("ORGID =", value, "ORGID");
            return (Criteria) this;
        }

        public Criteria andORGIDNotEqualTo(String value) {
            addCriterion("ORGID <>", value, "ORGID");
            return (Criteria) this;
        }

        public Criteria andORGIDGreaterThan(String value) {
            addCriterion("ORGID >", value, "ORGID");
            return (Criteria) this;
        }

        public Criteria andORGIDGreaterThanOrEqualTo(String value) {
            addCriterion("ORGID >=", value, "ORGID");
            return (Criteria) this;
        }

        public Criteria andORGIDLessThan(String value) {
            addCriterion("ORGID <", value, "ORGID");
            return (Criteria) this;
        }

        public Criteria andORGIDLessThanOrEqualTo(String value) {
            addCriterion("ORGID <=", value, "ORGID");
            return (Criteria) this;
        }

        public Criteria andORGIDLike(String value) {
            addCriterion("ORGID like", value, "ORGID");
            return (Criteria) this;
        }

        public Criteria andORGIDNotLike(String value) {
            addCriterion("ORGID not like", value, "ORGID");
            return (Criteria) this;
        }

        public Criteria andORGIDIn(List<String> values) {
            addCriterion("ORGID in", values, "ORGID");
            return (Criteria) this;
        }

        public Criteria andORGIDNotIn(List<String> values) {
            addCriterion("ORGID not in", values, "ORGID");
            return (Criteria) this;
        }

        public Criteria andORGIDBetween(String value1, String value2) {
            addCriterion("ORGID between", value1, value2, "ORGID");
            return (Criteria) this;
        }

        public Criteria andORGIDNotBetween(String value1, String value2) {
            addCriterion("ORGID not between", value1, value2, "ORGID");
            return (Criteria) this;
        }

        public Criteria andUSERTYPEIsNull() {
            addCriterion("USERTYPE is null");
            return (Criteria) this;
        }

        public Criteria andUSERTYPEIsNotNull() {
            addCriterion("USERTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUSERTYPEEqualTo(String value) {
            addCriterion("USERTYPE =", value, "USERTYPE");
            return (Criteria) this;
        }

        public Criteria andUSERTYPENotEqualTo(String value) {
            addCriterion("USERTYPE <>", value, "USERTYPE");
            return (Criteria) this;
        }

        public Criteria andUSERTYPEGreaterThan(String value) {
            addCriterion("USERTYPE >", value, "USERTYPE");
            return (Criteria) this;
        }

        public Criteria andUSERTYPEGreaterThanOrEqualTo(String value) {
            addCriterion("USERTYPE >=", value, "USERTYPE");
            return (Criteria) this;
        }

        public Criteria andUSERTYPELessThan(String value) {
            addCriterion("USERTYPE <", value, "USERTYPE");
            return (Criteria) this;
        }

        public Criteria andUSERTYPELessThanOrEqualTo(String value) {
            addCriterion("USERTYPE <=", value, "USERTYPE");
            return (Criteria) this;
        }

        public Criteria andUSERTYPELike(String value) {
            addCriterion("USERTYPE like", value, "USERTYPE");
            return (Criteria) this;
        }

        public Criteria andUSERTYPENotLike(String value) {
            addCriterion("USERTYPE not like", value, "USERTYPE");
            return (Criteria) this;
        }

        public Criteria andUSERTYPEIn(List<String> values) {
            addCriterion("USERTYPE in", values, "USERTYPE");
            return (Criteria) this;
        }

        public Criteria andUSERTYPENotIn(List<String> values) {
            addCriterion("USERTYPE not in", values, "USERTYPE");
            return (Criteria) this;
        }

        public Criteria andUSERTYPEBetween(String value1, String value2) {
            addCriterion("USERTYPE between", value1, value2, "USERTYPE");
            return (Criteria) this;
        }

        public Criteria andUSERTYPENotBetween(String value1, String value2) {
            addCriterion("USERTYPE not between", value1, value2, "USERTYPE");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMEIsNull() {
            addCriterion("DISPLAYNAME is null");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMEIsNotNull() {
            addCriterion("DISPLAYNAME is not null");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMEEqualTo(String value) {
            addCriterion("DISPLAYNAME =", value, "DISPLAYNAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMENotEqualTo(String value) {
            addCriterion("DISPLAYNAME <>", value, "DISPLAYNAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMEGreaterThan(String value) {
            addCriterion("DISPLAYNAME >", value, "DISPLAYNAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("DISPLAYNAME >=", value, "DISPLAYNAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMELessThan(String value) {
            addCriterion("DISPLAYNAME <", value, "DISPLAYNAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMELessThanOrEqualTo(String value) {
            addCriterion("DISPLAYNAME <=", value, "DISPLAYNAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMELike(String value) {
            addCriterion("DISPLAYNAME like", value, "DISPLAYNAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMENotLike(String value) {
            addCriterion("DISPLAYNAME not like", value, "DISPLAYNAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMEIn(List<String> values) {
            addCriterion("DISPLAYNAME in", values, "DISPLAYNAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMENotIn(List<String> values) {
            addCriterion("DISPLAYNAME not in", values, "DISPLAYNAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMEBetween(String value1, String value2) {
            addCriterion("DISPLAYNAME between", value1, value2, "DISPLAYNAME");
            return (Criteria) this;
        }

        public Criteria andDISPLAYNAMENotBetween(String value1, String value2) {
            addCriterion("DISPLAYNAME not between", value1, value2, "DISPLAYNAME");
            return (Criteria) this;
        }

        public Criteria andTELIsNull() {
            addCriterion("TEL is null");
            return (Criteria) this;
        }

        public Criteria andTELIsNotNull() {
            addCriterion("TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTELEqualTo(String value) {
            addCriterion("TEL =", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotEqualTo(String value) {
            addCriterion("TEL <>", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELGreaterThan(String value) {
            addCriterion("TEL >", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELLessThan(String value) {
            addCriterion("TEL <", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELLike(String value) {
            addCriterion("TEL like", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotLike(String value) {
            addCriterion("TEL not like", value, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELIn(List<String> values) {
            addCriterion("TEL in", values, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotIn(List<String> values) {
            addCriterion("TEL not in", values, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "TEL");
            return (Criteria) this;
        }

        public Criteria andTELNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "TEL");
            return (Criteria) this;
        }

        public Criteria andMOBILEIsNull() {
            addCriterion("MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andMOBILEIsNotNull() {
            addCriterion("MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andMOBILEEqualTo(String value) {
            addCriterion("MOBILE =", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILENotEqualTo(String value) {
            addCriterion("MOBILE <>", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILEGreaterThan(String value) {
            addCriterion("MOBILE >", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILEGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE >=", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILELessThan(String value) {
            addCriterion("MOBILE <", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILELessThanOrEqualTo(String value) {
            addCriterion("MOBILE <=", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILELike(String value) {
            addCriterion("MOBILE like", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILENotLike(String value) {
            addCriterion("MOBILE not like", value, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILEIn(List<String> values) {
            addCriterion("MOBILE in", values, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILENotIn(List<String> values) {
            addCriterion("MOBILE not in", values, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILEBetween(String value1, String value2) {
            addCriterion("MOBILE between", value1, value2, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andMOBILENotBetween(String value1, String value2) {
            addCriterion("MOBILE not between", value1, value2, "MOBILE");
            return (Criteria) this;
        }

        public Criteria andEMAILIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEMAILIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEMAILEqualTo(String value) {
            addCriterion("EMAIL =", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILGreaterThan(String value) {
            addCriterion("EMAIL >", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILLessThan(String value) {
            addCriterion("EMAIL <", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILLike(String value) {
            addCriterion("EMAIL like", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotLike(String value) {
            addCriterion("EMAIL not like", value, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILIn(List<String> values) {
            addCriterion("EMAIL in", values, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andEMAILNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "EMAIL");
            return (Criteria) this;
        }

        public Criteria andUSERADDRIsNull() {
            addCriterion("USERADDR is null");
            return (Criteria) this;
        }

        public Criteria andUSERADDRIsNotNull() {
            addCriterion("USERADDR is not null");
            return (Criteria) this;
        }

        public Criteria andUSERADDREqualTo(String value) {
            addCriterion("USERADDR =", value, "USERADDR");
            return (Criteria) this;
        }

        public Criteria andUSERADDRNotEqualTo(String value) {
            addCriterion("USERADDR <>", value, "USERADDR");
            return (Criteria) this;
        }

        public Criteria andUSERADDRGreaterThan(String value) {
            addCriterion("USERADDR >", value, "USERADDR");
            return (Criteria) this;
        }

        public Criteria andUSERADDRGreaterThanOrEqualTo(String value) {
            addCriterion("USERADDR >=", value, "USERADDR");
            return (Criteria) this;
        }

        public Criteria andUSERADDRLessThan(String value) {
            addCriterion("USERADDR <", value, "USERADDR");
            return (Criteria) this;
        }

        public Criteria andUSERADDRLessThanOrEqualTo(String value) {
            addCriterion("USERADDR <=", value, "USERADDR");
            return (Criteria) this;
        }

        public Criteria andUSERADDRLike(String value) {
            addCriterion("USERADDR like", value, "USERADDR");
            return (Criteria) this;
        }

        public Criteria andUSERADDRNotLike(String value) {
            addCriterion("USERADDR not like", value, "USERADDR");
            return (Criteria) this;
        }

        public Criteria andUSERADDRIn(List<String> values) {
            addCriterion("USERADDR in", values, "USERADDR");
            return (Criteria) this;
        }

        public Criteria andUSERADDRNotIn(List<String> values) {
            addCriterion("USERADDR not in", values, "USERADDR");
            return (Criteria) this;
        }

        public Criteria andUSERADDRBetween(String value1, String value2) {
            addCriterion("USERADDR between", value1, value2, "USERADDR");
            return (Criteria) this;
        }

        public Criteria andUSERADDRNotBetween(String value1, String value2) {
            addCriterion("USERADDR not between", value1, value2, "USERADDR");
            return (Criteria) this;
        }

        public Criteria andCREATORIDIsNull() {
            addCriterion("CREATORID is null");
            return (Criteria) this;
        }

        public Criteria andCREATORIDIsNotNull() {
            addCriterion("CREATORID is not null");
            return (Criteria) this;
        }

        public Criteria andCREATORIDEqualTo(String value) {
            addCriterion("CREATORID =", value, "CREATORID");
            return (Criteria) this;
        }

        public Criteria andCREATORIDNotEqualTo(String value) {
            addCriterion("CREATORID <>", value, "CREATORID");
            return (Criteria) this;
        }

        public Criteria andCREATORIDGreaterThan(String value) {
            addCriterion("CREATORID >", value, "CREATORID");
            return (Criteria) this;
        }

        public Criteria andCREATORIDGreaterThanOrEqualTo(String value) {
            addCriterion("CREATORID >=", value, "CREATORID");
            return (Criteria) this;
        }

        public Criteria andCREATORIDLessThan(String value) {
            addCriterion("CREATORID <", value, "CREATORID");
            return (Criteria) this;
        }

        public Criteria andCREATORIDLessThanOrEqualTo(String value) {
            addCriterion("CREATORID <=", value, "CREATORID");
            return (Criteria) this;
        }

        public Criteria andCREATORIDLike(String value) {
            addCriterion("CREATORID like", value, "CREATORID");
            return (Criteria) this;
        }

        public Criteria andCREATORIDNotLike(String value) {
            addCriterion("CREATORID not like", value, "CREATORID");
            return (Criteria) this;
        }

        public Criteria andCREATORIDIn(List<String> values) {
            addCriterion("CREATORID in", values, "CREATORID");
            return (Criteria) this;
        }

        public Criteria andCREATORIDNotIn(List<String> values) {
            addCriterion("CREATORID not in", values, "CREATORID");
            return (Criteria) this;
        }

        public Criteria andCREATORIDBetween(String value1, String value2) {
            addCriterion("CREATORID between", value1, value2, "CREATORID");
            return (Criteria) this;
        }

        public Criteria andCREATORIDNotBetween(String value1, String value2) {
            addCriterion("CREATORID not between", value1, value2, "CREATORID");
            return (Criteria) this;
        }

        public Criteria andFAILNOIsNull() {
            addCriterion("FAILNO is null");
            return (Criteria) this;
        }

        public Criteria andFAILNOIsNotNull() {
            addCriterion("FAILNO is not null");
            return (Criteria) this;
        }

        public Criteria andFAILNOEqualTo(Short value) {
            addCriterion("FAILNO =", value, "FAILNO");
            return (Criteria) this;
        }

        public Criteria andFAILNONotEqualTo(Short value) {
            addCriterion("FAILNO <>", value, "FAILNO");
            return (Criteria) this;
        }

        public Criteria andFAILNOGreaterThan(Short value) {
            addCriterion("FAILNO >", value, "FAILNO");
            return (Criteria) this;
        }

        public Criteria andFAILNOGreaterThanOrEqualTo(Short value) {
            addCriterion("FAILNO >=", value, "FAILNO");
            return (Criteria) this;
        }

        public Criteria andFAILNOLessThan(Short value) {
            addCriterion("FAILNO <", value, "FAILNO");
            return (Criteria) this;
        }

        public Criteria andFAILNOLessThanOrEqualTo(Short value) {
            addCriterion("FAILNO <=", value, "FAILNO");
            return (Criteria) this;
        }

        public Criteria andFAILNOIn(List<Short> values) {
            addCriterion("FAILNO in", values, "FAILNO");
            return (Criteria) this;
        }

        public Criteria andFAILNONotIn(List<Short> values) {
            addCriterion("FAILNO not in", values, "FAILNO");
            return (Criteria) this;
        }

        public Criteria andFAILNOBetween(Short value1, Short value2) {
            addCriterion("FAILNO between", value1, value2, "FAILNO");
            return (Criteria) this;
        }

        public Criteria andFAILNONotBetween(Short value1, Short value2) {
            addCriterion("FAILNO not between", value1, value2, "FAILNO");
            return (Criteria) this;
        }

        public Criteria andSALTIsNull() {
            addCriterion("SALT is null");
            return (Criteria) this;
        }

        public Criteria andSALTIsNotNull() {
            addCriterion("SALT is not null");
            return (Criteria) this;
        }

        public Criteria andSALTEqualTo(String value) {
            addCriterion("SALT =", value, "SALT");
            return (Criteria) this;
        }

        public Criteria andSALTNotEqualTo(String value) {
            addCriterion("SALT <>", value, "SALT");
            return (Criteria) this;
        }

        public Criteria andSALTGreaterThan(String value) {
            addCriterion("SALT >", value, "SALT");
            return (Criteria) this;
        }

        public Criteria andSALTGreaterThanOrEqualTo(String value) {
            addCriterion("SALT >=", value, "SALT");
            return (Criteria) this;
        }

        public Criteria andSALTLessThan(String value) {
            addCriterion("SALT <", value, "SALT");
            return (Criteria) this;
        }

        public Criteria andSALTLessThanOrEqualTo(String value) {
            addCriterion("SALT <=", value, "SALT");
            return (Criteria) this;
        }

        public Criteria andSALTLike(String value) {
            addCriterion("SALT like", value, "SALT");
            return (Criteria) this;
        }

        public Criteria andSALTNotLike(String value) {
            addCriterion("SALT not like", value, "SALT");
            return (Criteria) this;
        }

        public Criteria andSALTIn(List<String> values) {
            addCriterion("SALT in", values, "SALT");
            return (Criteria) this;
        }

        public Criteria andSALTNotIn(List<String> values) {
            addCriterion("SALT not in", values, "SALT");
            return (Criteria) this;
        }

        public Criteria andSALTBetween(String value1, String value2) {
            addCriterion("SALT between", value1, value2, "SALT");
            return (Criteria) this;
        }

        public Criteria andSALTNotBetween(String value1, String value2) {
            addCriterion("SALT not between", value1, value2, "SALT");
            return (Criteria) this;
        }

        public Criteria andIDCARDIsNull() {
            addCriterion("IDCARD is null");
            return (Criteria) this;
        }

        public Criteria andIDCARDIsNotNull() {
            addCriterion("IDCARD is not null");
            return (Criteria) this;
        }

        public Criteria andIDCARDEqualTo(String value) {
            addCriterion("IDCARD =", value, "IDCARD");
            return (Criteria) this;
        }

        public Criteria andIDCARDNotEqualTo(String value) {
            addCriterion("IDCARD <>", value, "IDCARD");
            return (Criteria) this;
        }

        public Criteria andIDCARDGreaterThan(String value) {
            addCriterion("IDCARD >", value, "IDCARD");
            return (Criteria) this;
        }

        public Criteria andIDCARDGreaterThanOrEqualTo(String value) {
            addCriterion("IDCARD >=", value, "IDCARD");
            return (Criteria) this;
        }

        public Criteria andIDCARDLessThan(String value) {
            addCriterion("IDCARD <", value, "IDCARD");
            return (Criteria) this;
        }

        public Criteria andIDCARDLessThanOrEqualTo(String value) {
            addCriterion("IDCARD <=", value, "IDCARD");
            return (Criteria) this;
        }

        public Criteria andIDCARDLike(String value) {
            addCriterion("IDCARD like", value, "IDCARD");
            return (Criteria) this;
        }

        public Criteria andIDCARDNotLike(String value) {
            addCriterion("IDCARD not like", value, "IDCARD");
            return (Criteria) this;
        }

        public Criteria andIDCARDIn(List<String> values) {
            addCriterion("IDCARD in", values, "IDCARD");
            return (Criteria) this;
        }

        public Criteria andIDCARDNotIn(List<String> values) {
            addCriterion("IDCARD not in", values, "IDCARD");
            return (Criteria) this;
        }

        public Criteria andIDCARDBetween(String value1, String value2) {
            addCriterion("IDCARD between", value1, value2, "IDCARD");
            return (Criteria) this;
        }

        public Criteria andIDCARDNotBetween(String value1, String value2) {
            addCriterion("IDCARD not between", value1, value2, "IDCARD");
            return (Criteria) this;
        }

        public Criteria andCAKEYIsNull() {
            addCriterion("CAKEY is null");
            return (Criteria) this;
        }

        public Criteria andCAKEYIsNotNull() {
            addCriterion("CAKEY is not null");
            return (Criteria) this;
        }

        public Criteria andCAKEYEqualTo(String value) {
            addCriterion("CAKEY =", value, "CAKEY");
            return (Criteria) this;
        }

        public Criteria andCAKEYNotEqualTo(String value) {
            addCriterion("CAKEY <>", value, "CAKEY");
            return (Criteria) this;
        }

        public Criteria andCAKEYGreaterThan(String value) {
            addCriterion("CAKEY >", value, "CAKEY");
            return (Criteria) this;
        }

        public Criteria andCAKEYGreaterThanOrEqualTo(String value) {
            addCriterion("CAKEY >=", value, "CAKEY");
            return (Criteria) this;
        }

        public Criteria andCAKEYLessThan(String value) {
            addCriterion("CAKEY <", value, "CAKEY");
            return (Criteria) this;
        }

        public Criteria andCAKEYLessThanOrEqualTo(String value) {
            addCriterion("CAKEY <=", value, "CAKEY");
            return (Criteria) this;
        }

        public Criteria andCAKEYLike(String value) {
            addCriterion("CAKEY like", value, "CAKEY");
            return (Criteria) this;
        }

        public Criteria andCAKEYNotLike(String value) {
            addCriterion("CAKEY not like", value, "CAKEY");
            return (Criteria) this;
        }

        public Criteria andCAKEYIn(List<String> values) {
            addCriterion("CAKEY in", values, "CAKEY");
            return (Criteria) this;
        }

        public Criteria andCAKEYNotIn(List<String> values) {
            addCriterion("CAKEY not in", values, "CAKEY");
            return (Criteria) this;
        }

        public Criteria andCAKEYBetween(String value1, String value2) {
            addCriterion("CAKEY between", value1, value2, "CAKEY");
            return (Criteria) this;
        }

        public Criteria andCAKEYNotBetween(String value1, String value2) {
            addCriterion("CAKEY not between", value1, value2, "CAKEY");
            return (Criteria) this;
        }

        public Criteria andLOGINTIMEIsNull() {
            addCriterion("LOGINTIME is null");
            return (Criteria) this;
        }

        public Criteria andLOGINTIMEIsNotNull() {
            addCriterion("LOGINTIME is not null");
            return (Criteria) this;
        }

        public Criteria andLOGINTIMEEqualTo(Date value) {
            addCriterion("LOGINTIME =", value, "LOGINTIME");
            return (Criteria) this;
        }

        public Criteria andLOGINTIMENotEqualTo(Date value) {
            addCriterion("LOGINTIME <>", value, "LOGINTIME");
            return (Criteria) this;
        }

        public Criteria andLOGINTIMEGreaterThan(Date value) {
            addCriterion("LOGINTIME >", value, "LOGINTIME");
            return (Criteria) this;
        }

        public Criteria andLOGINTIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("LOGINTIME >=", value, "LOGINTIME");
            return (Criteria) this;
        }

        public Criteria andLOGINTIMELessThan(Date value) {
            addCriterion("LOGINTIME <", value, "LOGINTIME");
            return (Criteria) this;
        }

        public Criteria andLOGINTIMELessThanOrEqualTo(Date value) {
            addCriterion("LOGINTIME <=", value, "LOGINTIME");
            return (Criteria) this;
        }

        public Criteria andLOGINTIMEIn(List<Date> values) {
            addCriterion("LOGINTIME in", values, "LOGINTIME");
            return (Criteria) this;
        }

        public Criteria andLOGINTIMENotIn(List<Date> values) {
            addCriterion("LOGINTIME not in", values, "LOGINTIME");
            return (Criteria) this;
        }

        public Criteria andLOGINTIMEBetween(Date value1, Date value2) {
            addCriterion("LOGINTIME between", value1, value2, "LOGINTIME");
            return (Criteria) this;
        }

        public Criteria andLOGINTIMENotBetween(Date value1, Date value2) {
            addCriterion("LOGINTIME not between", value1, value2, "LOGINTIME");
            return (Criteria) this;
        }

        public Criteria andUSERID01IsNull() {
            addCriterion("USERID01 is null");
            return (Criteria) this;
        }

        public Criteria andUSERID01IsNotNull() {
            addCriterion("USERID01 is not null");
            return (Criteria) this;
        }

        public Criteria andUSERID01EqualTo(String value) {
            addCriterion("USERID01 =", value, "USERID01");
            return (Criteria) this;
        }

        public Criteria andUSERID01NotEqualTo(String value) {
            addCriterion("USERID01 <>", value, "USERID01");
            return (Criteria) this;
        }

        public Criteria andUSERID01GreaterThan(String value) {
            addCriterion("USERID01 >", value, "USERID01");
            return (Criteria) this;
        }

        public Criteria andUSERID01GreaterThanOrEqualTo(String value) {
            addCriterion("USERID01 >=", value, "USERID01");
            return (Criteria) this;
        }

        public Criteria andUSERID01LessThan(String value) {
            addCriterion("USERID01 <", value, "USERID01");
            return (Criteria) this;
        }

        public Criteria andUSERID01LessThanOrEqualTo(String value) {
            addCriterion("USERID01 <=", value, "USERID01");
            return (Criteria) this;
        }

        public Criteria andUSERID01Like(String value) {
            addCriterion("USERID01 like", value, "USERID01");
            return (Criteria) this;
        }

        public Criteria andUSERID01NotLike(String value) {
            addCriterion("USERID01 not like", value, "USERID01");
            return (Criteria) this;
        }

        public Criteria andUSERID01In(List<String> values) {
            addCriterion("USERID01 in", values, "USERID01");
            return (Criteria) this;
        }

        public Criteria andUSERID01NotIn(List<String> values) {
            addCriterion("USERID01 not in", values, "USERID01");
            return (Criteria) this;
        }

        public Criteria andUSERID01Between(String value1, String value2) {
            addCriterion("USERID01 between", value1, value2, "USERID01");
            return (Criteria) this;
        }

        public Criteria andUSERID01NotBetween(String value1, String value2) {
            addCriterion("USERID01 not between", value1, value2, "USERID01");
            return (Criteria) this;
        }

        public Criteria andUSERID02IsNull() {
            addCriterion("USERID02 is null");
            return (Criteria) this;
        }

        public Criteria andUSERID02IsNotNull() {
            addCriterion("USERID02 is not null");
            return (Criteria) this;
        }

        public Criteria andUSERID02EqualTo(String value) {
            addCriterion("USERID02 =", value, "USERID02");
            return (Criteria) this;
        }

        public Criteria andUSERID02NotEqualTo(String value) {
            addCriterion("USERID02 <>", value, "USERID02");
            return (Criteria) this;
        }

        public Criteria andUSERID02GreaterThan(String value) {
            addCriterion("USERID02 >", value, "USERID02");
            return (Criteria) this;
        }

        public Criteria andUSERID02GreaterThanOrEqualTo(String value) {
            addCriterion("USERID02 >=", value, "USERID02");
            return (Criteria) this;
        }

        public Criteria andUSERID02LessThan(String value) {
            addCriterion("USERID02 <", value, "USERID02");
            return (Criteria) this;
        }

        public Criteria andUSERID02LessThanOrEqualTo(String value) {
            addCriterion("USERID02 <=", value, "USERID02");
            return (Criteria) this;
        }

        public Criteria andUSERID02Like(String value) {
            addCriterion("USERID02 like", value, "USERID02");
            return (Criteria) this;
        }

        public Criteria andUSERID02NotLike(String value) {
            addCriterion("USERID02 not like", value, "USERID02");
            return (Criteria) this;
        }

        public Criteria andUSERID02In(List<String> values) {
            addCriterion("USERID02 in", values, "USERID02");
            return (Criteria) this;
        }

        public Criteria andUSERID02NotIn(List<String> values) {
            addCriterion("USERID02 not in", values, "USERID02");
            return (Criteria) this;
        }

        public Criteria andUSERID02Between(String value1, String value2) {
            addCriterion("USERID02 between", value1, value2, "USERID02");
            return (Criteria) this;
        }

        public Criteria andUSERID02NotBetween(String value1, String value2) {
            addCriterion("USERID02 not between", value1, value2, "USERID02");
            return (Criteria) this;
        }

        public Criteria andUSERID03IsNull() {
            addCriterion("USERID03 is null");
            return (Criteria) this;
        }

        public Criteria andUSERID03IsNotNull() {
            addCriterion("USERID03 is not null");
            return (Criteria) this;
        }

        public Criteria andUSERID03EqualTo(String value) {
            addCriterion("USERID03 =", value, "USERID03");
            return (Criteria) this;
        }

        public Criteria andUSERID03NotEqualTo(String value) {
            addCriterion("USERID03 <>", value, "USERID03");
            return (Criteria) this;
        }

        public Criteria andUSERID03GreaterThan(String value) {
            addCriterion("USERID03 >", value, "USERID03");
            return (Criteria) this;
        }

        public Criteria andUSERID03GreaterThanOrEqualTo(String value) {
            addCriterion("USERID03 >=", value, "USERID03");
            return (Criteria) this;
        }

        public Criteria andUSERID03LessThan(String value) {
            addCriterion("USERID03 <", value, "USERID03");
            return (Criteria) this;
        }

        public Criteria andUSERID03LessThanOrEqualTo(String value) {
            addCriterion("USERID03 <=", value, "USERID03");
            return (Criteria) this;
        }

        public Criteria andUSERID03Like(String value) {
            addCriterion("USERID03 like", value, "USERID03");
            return (Criteria) this;
        }

        public Criteria andUSERID03NotLike(String value) {
            addCriterion("USERID03 not like", value, "USERID03");
            return (Criteria) this;
        }

        public Criteria andUSERID03In(List<String> values) {
            addCriterion("USERID03 in", values, "USERID03");
            return (Criteria) this;
        }

        public Criteria andUSERID03NotIn(List<String> values) {
            addCriterion("USERID03 not in", values, "USERID03");
            return (Criteria) this;
        }

        public Criteria andUSERID03Between(String value1, String value2) {
            addCriterion("USERID03 between", value1, value2, "USERID03");
            return (Criteria) this;
        }

        public Criteria andUSERID03NotBetween(String value1, String value2) {
            addCriterion("USERID03 not between", value1, value2, "USERID03");
            return (Criteria) this;
        }

        public Criteria andUSERQXIsNull() {
            addCriterion("USERQX is null");
            return (Criteria) this;
        }

        public Criteria andUSERQXIsNotNull() {
            addCriterion("USERQX is not null");
            return (Criteria) this;
        }

        public Criteria andUSERQXEqualTo(String value) {
            addCriterion("USERQX =", value, "USERQX");
            return (Criteria) this;
        }

        public Criteria andUSERQXNotEqualTo(String value) {
            addCriterion("USERQX <>", value, "USERQX");
            return (Criteria) this;
        }

        public Criteria andUSERQXGreaterThan(String value) {
            addCriterion("USERQX >", value, "USERQX");
            return (Criteria) this;
        }

        public Criteria andUSERQXGreaterThanOrEqualTo(String value) {
            addCriterion("USERQX >=", value, "USERQX");
            return (Criteria) this;
        }

        public Criteria andUSERQXLessThan(String value) {
            addCriterion("USERQX <", value, "USERQX");
            return (Criteria) this;
        }

        public Criteria andUSERQXLessThanOrEqualTo(String value) {
            addCriterion("USERQX <=", value, "USERQX");
            return (Criteria) this;
        }

        public Criteria andUSERQXLike(String value) {
            addCriterion("USERQX like", value, "USERQX");
            return (Criteria) this;
        }

        public Criteria andUSERQXNotLike(String value) {
            addCriterion("USERQX not like", value, "USERQX");
            return (Criteria) this;
        }

        public Criteria andUSERQXIn(List<String> values) {
            addCriterion("USERQX in", values, "USERQX");
            return (Criteria) this;
        }

        public Criteria andUSERQXNotIn(List<String> values) {
            addCriterion("USERQX not in", values, "USERQX");
            return (Criteria) this;
        }

        public Criteria andUSERQXBetween(String value1, String value2) {
            addCriterion("USERQX between", value1, value2, "USERQX");
            return (Criteria) this;
        }

        public Criteria andUSERQXNotBetween(String value1, String value2) {
            addCriterion("USERQX not between", value1, value2, "USERQX");
            return (Criteria) this;
        }

        public Criteria andUSERKINDIsNull() {
            addCriterion("USERKIND is null");
            return (Criteria) this;
        }

        public Criteria andUSERKINDIsNotNull() {
            addCriterion("USERKIND is not null");
            return (Criteria) this;
        }

        public Criteria andUSERKINDEqualTo(String value) {
            addCriterion("USERKIND =", value, "USERKIND");
            return (Criteria) this;
        }

        public Criteria andUSERKINDNotEqualTo(String value) {
            addCriterion("USERKIND <>", value, "USERKIND");
            return (Criteria) this;
        }

        public Criteria andUSERKINDGreaterThan(String value) {
            addCriterion("USERKIND >", value, "USERKIND");
            return (Criteria) this;
        }

        public Criteria andUSERKINDGreaterThanOrEqualTo(String value) {
            addCriterion("USERKIND >=", value, "USERKIND");
            return (Criteria) this;
        }

        public Criteria andUSERKINDLessThan(String value) {
            addCriterion("USERKIND <", value, "USERKIND");
            return (Criteria) this;
        }

        public Criteria andUSERKINDLessThanOrEqualTo(String value) {
            addCriterion("USERKIND <=", value, "USERKIND");
            return (Criteria) this;
        }

        public Criteria andUSERKINDLike(String value) {
            addCriterion("USERKIND like", value, "USERKIND");
            return (Criteria) this;
        }

        public Criteria andUSERKINDNotLike(String value) {
            addCriterion("USERKIND not like", value, "USERKIND");
            return (Criteria) this;
        }

        public Criteria andUSERKINDIn(List<String> values) {
            addCriterion("USERKIND in", values, "USERKIND");
            return (Criteria) this;
        }

        public Criteria andUSERKINDNotIn(List<String> values) {
            addCriterion("USERKIND not in", values, "USERKIND");
            return (Criteria) this;
        }

        public Criteria andUSERKINDBetween(String value1, String value2) {
            addCriterion("USERKIND between", value1, value2, "USERKIND");
            return (Criteria) this;
        }

        public Criteria andUSERKINDNotBetween(String value1, String value2) {
            addCriterion("USERKIND not between", value1, value2, "USERKIND");
            return (Criteria) this;
        }

        public Criteria andLASTEDITTIMEIsNull() {
            addCriterion("LASTEDITTIME is null");
            return (Criteria) this;
        }

        public Criteria andLASTEDITTIMEIsNotNull() {
            addCriterion("LASTEDITTIME is not null");
            return (Criteria) this;
        }

        public Criteria andLASTEDITTIMEEqualTo(Date value) {
            addCriterion("LASTEDITTIME =", value, "LASTEDITTIME");
            return (Criteria) this;
        }

        public Criteria andLASTEDITTIMENotEqualTo(Date value) {
            addCriterion("LASTEDITTIME <>", value, "LASTEDITTIME");
            return (Criteria) this;
        }

        public Criteria andLASTEDITTIMEGreaterThan(Date value) {
            addCriterion("LASTEDITTIME >", value, "LASTEDITTIME");
            return (Criteria) this;
        }

        public Criteria andLASTEDITTIMEGreaterThanOrEqualTo(Date value) {
            addCriterion("LASTEDITTIME >=", value, "LASTEDITTIME");
            return (Criteria) this;
        }

        public Criteria andLASTEDITTIMELessThan(Date value) {
            addCriterion("LASTEDITTIME <", value, "LASTEDITTIME");
            return (Criteria) this;
        }

        public Criteria andLASTEDITTIMELessThanOrEqualTo(Date value) {
            addCriterion("LASTEDITTIME <=", value, "LASTEDITTIME");
            return (Criteria) this;
        }

        public Criteria andLASTEDITTIMEIn(List<Date> values) {
            addCriterion("LASTEDITTIME in", values, "LASTEDITTIME");
            return (Criteria) this;
        }

        public Criteria andLASTEDITTIMENotIn(List<Date> values) {
            addCriterion("LASTEDITTIME not in", values, "LASTEDITTIME");
            return (Criteria) this;
        }

        public Criteria andLASTEDITTIMEBetween(Date value1, Date value2) {
            addCriterion("LASTEDITTIME between", value1, value2, "LASTEDITTIME");
            return (Criteria) this;
        }

        public Criteria andLASTEDITTIMENotBetween(Date value1, Date value2) {
            addCriterion("LASTEDITTIME not between", value1, value2, "LASTEDITTIME");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDIsNull() {
            addCriterion("FORCEEDITPWD is null");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDIsNotNull() {
            addCriterion("FORCEEDITPWD is not null");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDEqualTo(String value) {
            addCriterion("FORCEEDITPWD =", value, "FORCEEDITPWD");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDNotEqualTo(String value) {
            addCriterion("FORCEEDITPWD <>", value, "FORCEEDITPWD");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDGreaterThan(String value) {
            addCriterion("FORCEEDITPWD >", value, "FORCEEDITPWD");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDGreaterThanOrEqualTo(String value) {
            addCriterion("FORCEEDITPWD >=", value, "FORCEEDITPWD");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDLessThan(String value) {
            addCriterion("FORCEEDITPWD <", value, "FORCEEDITPWD");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDLessThanOrEqualTo(String value) {
            addCriterion("FORCEEDITPWD <=", value, "FORCEEDITPWD");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDLike(String value) {
            addCriterion("FORCEEDITPWD like", value, "FORCEEDITPWD");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDNotLike(String value) {
            addCriterion("FORCEEDITPWD not like", value, "FORCEEDITPWD");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDIn(List<String> values) {
            addCriterion("FORCEEDITPWD in", values, "FORCEEDITPWD");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDNotIn(List<String> values) {
            addCriterion("FORCEEDITPWD not in", values, "FORCEEDITPWD");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDBetween(String value1, String value2) {
            addCriterion("FORCEEDITPWD between", value1, value2, "FORCEEDITPWD");
            return (Criteria) this;
        }

        public Criteria andFORCEEDITPWDNotBetween(String value1, String value2) {
            addCriterion("FORCEEDITPWD not between", value1, value2, "FORCEEDITPWD");
            return (Criteria) this;
        }

        public Criteria andAAZ198IsNull() {
            addCriterion("AAZ198 is null");
            return (Criteria) this;
        }

        public Criteria andAAZ198IsNotNull() {
            addCriterion("AAZ198 is not null");
            return (Criteria) this;
        }

        public Criteria andAAZ198EqualTo(BigDecimal value) {
            addCriterion("AAZ198 =", value, "AAZ198");
            return (Criteria) this;
        }

        public Criteria andAAZ198NotEqualTo(BigDecimal value) {
            addCriterion("AAZ198 <>", value, "AAZ198");
            return (Criteria) this;
        }

        public Criteria andAAZ198GreaterThan(BigDecimal value) {
            addCriterion("AAZ198 >", value, "AAZ198");
            return (Criteria) this;
        }

        public Criteria andAAZ198GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AAZ198 >=", value, "AAZ198");
            return (Criteria) this;
        }

        public Criteria andAAZ198LessThan(BigDecimal value) {
            addCriterion("AAZ198 <", value, "AAZ198");
            return (Criteria) this;
        }

        public Criteria andAAZ198LessThanOrEqualTo(BigDecimal value) {
            addCriterion("AAZ198 <=", value, "AAZ198");
            return (Criteria) this;
        }

        public Criteria andAAZ198In(List<BigDecimal> values) {
            addCriterion("AAZ198 in", values, "AAZ198");
            return (Criteria) this;
        }

        public Criteria andAAZ198NotIn(List<BigDecimal> values) {
            addCriterion("AAZ198 not in", values, "AAZ198");
            return (Criteria) this;
        }

        public Criteria andAAZ198Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("AAZ198 between", value1, value2, "AAZ198");
            return (Criteria) this;
        }

        public Criteria andAAZ198NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AAZ198 not between", value1, value2, "AAZ198");
            return (Criteria) this;
        }

        public Criteria andREMARKIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andREMARKIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andREMARKEqualTo(String value) {
            addCriterion("REMARK =", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKGreaterThan(String value) {
            addCriterion("REMARK >", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLessThan(String value) {
            addCriterion("REMARK <", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKLike(String value) {
            addCriterion("REMARK like", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotLike(String value) {
            addCriterion("REMARK not like", value, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKIn(List<String> values) {
            addCriterion("REMARK in", values, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "REMARK");
            return (Criteria) this;
        }

        public Criteria andREMARKNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "REMARK");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 01 00:20:35 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:20:35 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}