package com.jxufe.dao.eva_sso;

import com.jxufe.entity.eva_sso.SysUser;
import java.util.List;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    int deleteByPrimaryKey(String USERID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    SysUser selectByPrimaryKey(String USERID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    List<SysUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVA_SSO.SYSUSER
     *
     * @mbg.generated Fri Sep 01 00:29:23 CST 2017
     */
    int updateByPrimaryKey(SysUser record);
}